name: Package Application with Pyinstaller

on:
  push:
    branches:
      - main

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Package application
      run:
        pyinstaller -i icons/icon.ico -w --clean --log-level WARN main.py

    - name: Copy files
      run:
        xcopy /y /e /i data dist\main\data
    
    - name: Create archive
      uses: vimtor/action-zip@v1.1
      with:
        files: ./dist/main
        dest: OI_Dictionary.zip

    - name: Upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: alpha
        prerelease: true
        title: Development Build
        files: OI_Dictionary.zip